platform :ios,	'7.0'
pod 'SDWebImage',	'~> 3.7.1'
pod 'AFNetworking',	'~> 2.5.0'
pod 'MBProgressHUD',	'~> 0.9'
pod 'SVPullToRefresh',	'~> 0.4.1'
pod 'MJRefresh', 	'~> 1.4.5'
pod 'FMDB', 		'~> 2.5'
pod 'QBImagePickerController', '~> 2.2.2'
pod 'INTULocationManager', '~> 3.0.1'
pod 'Masonry', '~> 0.6.3'
pod 'YRADScrollView', '~> 1.0.0'
pod 'UIView+NibLoading', '~> 1.2.0'
pod 'HYBMasonryAutoCellHeight', '~> 0.0.1'
pod 'MJExtension', '~> 2.5.14'
pod 'IQKeyboardManager'
pod 'TTCategory', '~> 1.0.2’